//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGeFin.Reporting.DAT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SisGeFinEntities : DbContext
    {
        //public SisGeFinEntities()
        //    : base("name=SisGeFinEntities")
        //{
        //}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vPatriminioInventario> vPatriminioInventarios { get; set; }
        public virtual DbSet<ReporteCR> ReportesCR { get; set; }
    
        public virtual ObjectResult<vKardexPatrimonio> uspKardexPatrimonio1ReporteCsv(string param)
        {
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vKardexPatrimonio>("uspKardexPatrimonio1ReporteCsv", paramParameter);
        }
    }
}
