//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGeFin.Reporting.DAT
{
    using System;
    
    public partial class vKardexPatrimonio
    {
        public int IdMovimInv { get; set; }
        public string IdPatrimonio { get; set; }
        public string NombrePatrimon { get; set; }
        public string FechaCompra { get; set; }
        public string FechaAlta { get; set; }
        public string IdCtaMayor { get; set; }
        public string NombreCtaMayor { get; set; }
        public string IdSubCtaCon { get; set; }
        public string NombreSubCta { get; set; }
        public int NumeroMovim { get; set; }
        public string FechaMovim { get; set; }
        public string SerieItem { get; set; }
        public string TipoIngreso { get; set; }
        public string NombreMarca { get; set; }
        public string NombreModelo { get; set; }
        public string NomEstConserv { get; set; }
        public string Grupo { get; set; }
        public int CorreMovim { get; set; }
        public string FechaMovim1 { get; set; }
        public string MotivoMovim { get; set; }
        public string NomTipoMovim { get; set; }
        public string NombreRepara { get; set; }
        public string NomProvOrig { get; set; }
        public string NomUbicOrig { get; set; }
        public string NomOficOrig { get; set; }
        public string NomProvDest { get; set; }
        public string NomUbicDest { get; set; }
        public string NomOficDest { get; set; }
        public string DocumReferen { get; set; }
    }
}
