//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGeFin.Reporting.DAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPatriminioInventario
    {
        public int IdMovimInv { get; set; }
        public int IdMovimCab { get; set; }
        public int IdMovimDet { get; set; }
        public string NombreFamilia { get; set; }
        public string NombreClase { get; set; }
        public string NombreGrupo { get; set; }
        public string NroOc { get; set; }
        public string FechaEmision { get; set; }
        public string FechaMovim { get; set; }
        public string IdCtaMayor { get; set; }
        public string NombreCtaMayor { get; set; }
        public string IdSubCta { get; set; }
        public string NombreSubCta { get; set; }
        public string CuentaContable { get; set; }
        public string CodigoPatrimon { get; set; }
        public string DescripcionMovim { get; set; }
        public string NombreMarca { get; set; }
        public string NombreModelo { get; set; }
        public string NombreResponCab { get; set; }
        public string NombreResponsable { get; set; }
        public string NombreCompleto { get; set; }
        public string UsuarioItem { get; set; }
        public string NomEstadoC { get; set; }
        public string NomEstadoD { get; set; }
        public string NombreOficina { get; set; }
        public string NombreUbicacion { get; set; }
        public string CausaIngreso { get; set; }
        public string TipoIngreso { get; set; }
        public string SerieItem { get; set; }
        public int MesProceso { get; set; }
        public decimal OcNea { get; set; }
        public string FechaNea { get; set; }
        public decimal ValorCompra { get; set; }
        public decimal ValorInicial { get; set; }
        public string IdTipoMovim { get; set; }
        public int IdUbicacion { get; set; }
        public int IdResponsable { get; set; }
        public int IdResponItem { get; set; }
        public int AñoEjecuc { get; set; }
        public int IdEstadoC { get; set; }
        public int IdEstadoD { get; set; }
        public int IdOficina { get; set; }
        public int IdUsuario { get; set; }
        public string IdFamilia { get; set; }
        public string IdClase { get; set; }
        public string IdGrupo { get; set; }
        public string NombreResponFisica { get; set; }
        public string NomEstConserv { get; set; }
        public int IdEstConserv { get; set; }
    }
}
